// Code generated by protoc-gen-go.
// source: STS.proto
// DO NOT EDIT!

package common

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type STSup_JoinRequest_JoinType int32

const (
	STSup_JoinRequest_JOIN   STSup_JoinRequest_JoinType = 0
	STSup_JoinRequest_REJOIN STSup_JoinRequest_JoinType = 1
)

var STSup_JoinRequest_JoinType_name = map[int32]string{
	0: "JOIN",
	1: "REJOIN",
}
var STSup_JoinRequest_JoinType_value = map[string]int32{
	"JOIN":   0,
	"REJOIN": 1,
}

func (x STSup_JoinRequest_JoinType) Enum() *STSup_JoinRequest_JoinType {
	p := new(STSup_JoinRequest_JoinType)
	*p = x
	return p
}
func (x STSup_JoinRequest_JoinType) String() string {
	return proto.EnumName(STSup_JoinRequest_JoinType_name, int32(x))
}
func (x STSup_JoinRequest_JoinType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *STSup_JoinRequest_JoinType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STSup_JoinRequest_JoinType_value, data, "STSup_JoinRequest_JoinType")
	if err != nil {
		return err
	}
	*x = STSup_JoinRequest_JoinType(value)
	return nil
}

type STSup_Connection_ConnectionCommand int32

const (
	STSup_Connection_CONNECT    STSup_Connection_ConnectionCommand = 0
	STSup_Connection_DISCONNECT STSup_Connection_ConnectionCommand = 1
)

var STSup_Connection_ConnectionCommand_name = map[int32]string{
	0: "CONNECT",
	1: "DISCONNECT",
}
var STSup_Connection_ConnectionCommand_value = map[string]int32{
	"CONNECT":    0,
	"DISCONNECT": 1,
}

func (x STSup_Connection_ConnectionCommand) Enum() *STSup_Connection_ConnectionCommand {
	p := new(STSup_Connection_ConnectionCommand)
	*p = x
	return p
}
func (x STSup_Connection_ConnectionCommand) String() string {
	return proto.EnumName(STSup_Connection_ConnectionCommand_name, int32(x))
}
func (x STSup_Connection_ConnectionCommand) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *STSup_Connection_ConnectionCommand) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STSup_Connection_ConnectionCommand_value, data, "STSup_Connection_ConnectionCommand")
	if err != nil {
		return err
	}
	*x = STSup_Connection_ConnectionCommand(value)
	return nil
}

type STSdown_JoinResponse_Type int32

const (
	STSdown_JoinResponse_JOIN_ACCEPTED   STSdown_JoinResponse_Type = 0
	STSdown_JoinResponse_REJOIN_ACCEPTED STSdown_JoinResponse_Type = 1
	STSdown_JoinResponse_JOIN_REJECTED   STSdown_JoinResponse_Type = 2
)

var STSdown_JoinResponse_Type_name = map[int32]string{
	0: "JOIN_ACCEPTED",
	1: "REJOIN_ACCEPTED",
	2: "JOIN_REJECTED",
}
var STSdown_JoinResponse_Type_value = map[string]int32{
	"JOIN_ACCEPTED":   0,
	"REJOIN_ACCEPTED": 1,
	"JOIN_REJECTED":   2,
}

func (x STSdown_JoinResponse_Type) Enum() *STSdown_JoinResponse_Type {
	p := new(STSdown_JoinResponse_Type)
	*p = x
	return p
}
func (x STSdown_JoinResponse_Type) String() string {
	return proto.EnumName(STSdown_JoinResponse_Type_name, int32(x))
}
func (x STSdown_JoinResponse_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *STSdown_JoinResponse_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STSdown_JoinResponse_Type_value, data, "STSdown_JoinResponse_Type")
	if err != nil {
		return err
	}
	*x = STSdown_JoinResponse_Type(value)
	return nil
}

type STSdown_VisualSensors_SpaceObject_Type int32

const (
	STSdown_VisualSensors_SpaceObject_SHIP     STSdown_VisualSensors_SpaceObject_Type = 0
	STSdown_VisualSensors_SpaceObject_ASTEROID STSdown_VisualSensors_SpaceObject_Type = 1
)

var STSdown_VisualSensors_SpaceObject_Type_name = map[int32]string{
	0: "SHIP",
	1: "ASTEROID",
}
var STSdown_VisualSensors_SpaceObject_Type_value = map[string]int32{
	"SHIP":     0,
	"ASTEROID": 1,
}

func (x STSdown_VisualSensors_SpaceObject_Type) Enum() *STSdown_VisualSensors_SpaceObject_Type {
	p := new(STSdown_VisualSensors_SpaceObject_Type)
	*p = x
	return p
}
func (x STSdown_VisualSensors_SpaceObject_Type) String() string {
	return proto.EnumName(STSdown_VisualSensors_SpaceObject_Type_name, int32(x))
}
func (x STSdown_VisualSensors_SpaceObject_Type) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *STSdown_VisualSensors_SpaceObject_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(STSdown_VisualSensors_SpaceObject_Type_value, data, "STSdown_VisualSensors_SpaceObject_Type")
	if err != nil {
		return err
	}
	*x = STSdown_VisualSensors_SpaceObject_Type(value)
	return nil
}

type STSup struct {
	Rcon              *STSup_RCon              `protobuf:"bytes,1,opt,name=rcon" json:"rcon,omitempty"`
	JoinRequest       *STSup_JoinRequest       `protobuf:"bytes,2,opt,name=joinRequest" json:"joinRequest,omitempty"`
	Connection        *STSup_Connection        `protobuf:"bytes,3,opt,name=connection" json:"connection,omitempty"`
	Lobby             *STSup_Lobby             `protobuf:"bytes,4,opt,name=lobby" json:"lobby,omitempty"`
	Subscribe         *STSup_Subscribe         `protobuf:"bytes,5,opt,name=subscribe" json:"subscribe,omitempty"`
	Reactor           *STSup_Reactor           `protobuf:"bytes,6,opt,name=reactor" json:"reactor,omitempty"`
	PowerDistribution *STSup_PowerDistribution `protobuf:"bytes,7,opt,name=powerDistribution" json:"powerDistribution,omitempty"`
	Engines           *STSup_Engines           `protobuf:"bytes,8,opt,name=engines" json:"engines,omitempty"`
	Thrusters         *STSup_Thrusters         `protobuf:"bytes,9,opt,name=thrusters" json:"thrusters,omitempty"`
	XXX_unrecognized  []byte                   `json:"-"`
}

func (m *STSup) Reset()         { *m = STSup{} }
func (m *STSup) String() string { return proto.CompactTextString(m) }
func (*STSup) ProtoMessage()    {}

func (m *STSup) GetRcon() *STSup_RCon {
	if m != nil {
		return m.Rcon
	}
	return nil
}

func (m *STSup) GetJoinRequest() *STSup_JoinRequest {
	if m != nil {
		return m.JoinRequest
	}
	return nil
}

func (m *STSup) GetConnection() *STSup_Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *STSup) GetLobby() *STSup_Lobby {
	if m != nil {
		return m.Lobby
	}
	return nil
}

func (m *STSup) GetSubscribe() *STSup_Subscribe {
	if m != nil {
		return m.Subscribe
	}
	return nil
}

func (m *STSup) GetReactor() *STSup_Reactor {
	if m != nil {
		return m.Reactor
	}
	return nil
}

func (m *STSup) GetPowerDistribution() *STSup_PowerDistribution {
	if m != nil {
		return m.PowerDistribution
	}
	return nil
}

func (m *STSup) GetEngines() *STSup_Engines {
	if m != nil {
		return m.Engines
	}
	return nil
}

func (m *STSup) GetThrusters() *STSup_Thrusters {
	if m != nil {
		return m.Thrusters
	}
	return nil
}

type STSup_RCon struct {
	Command          *string `protobuf:"bytes,1,opt,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STSup_RCon) Reset()         { *m = STSup_RCon{} }
func (m *STSup_RCon) String() string { return proto.CompactTextString(m) }
func (*STSup_RCon) ProtoMessage()    {}

func (m *STSup_RCon) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

type STSup_JoinRequest struct {
	Type             *STSup_JoinRequest_JoinType `protobuf:"varint,1,req,name=type,enum=common.STSup_JoinRequest_JoinType" json:"type,omitempty"`
	RejoinToken      *string                     `protobuf:"bytes,2,opt,name=rejoinToken" json:"rejoinToken,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *STSup_JoinRequest) Reset()         { *m = STSup_JoinRequest{} }
func (m *STSup_JoinRequest) String() string { return proto.CompactTextString(m) }
func (*STSup_JoinRequest) ProtoMessage()    {}

func (m *STSup_JoinRequest) GetType() STSup_JoinRequest_JoinType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return STSup_JoinRequest_JOIN
}

func (m *STSup_JoinRequest) GetRejoinToken() string {
	if m != nil && m.RejoinToken != nil {
		return *m.RejoinToken
	}
	return ""
}

type STSup_Connection struct {
	ConnectionCommand *STSup_Connection_ConnectionCommand `protobuf:"varint,1,opt,name=connectionCommand,enum=common.STSup_Connection_ConnectionCommand" json:"connectionCommand,omitempty"`
	Host              *string                             `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port              *uint32                             `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	XXX_unrecognized  []byte                              `json:"-"`
}

func (m *STSup_Connection) Reset()         { *m = STSup_Connection{} }
func (m *STSup_Connection) String() string { return proto.CompactTextString(m) }
func (*STSup_Connection) ProtoMessage()    {}

func (m *STSup_Connection) GetConnectionCommand() STSup_Connection_ConnectionCommand {
	if m != nil && m.ConnectionCommand != nil {
		return *m.ConnectionCommand
	}
	return STSup_Connection_CONNECT
}

func (m *STSup_Connection) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *STSup_Connection) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

type STSup_Lobby struct {
	ReadyState       *bool   `protobuf:"varint,1,opt,name=readyState" json:"readyState,omitempty"`
	ShipName         *string `protobuf:"bytes,2,opt,name=shipName" json:"shipName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STSup_Lobby) Reset()         { *m = STSup_Lobby{} }
func (m *STSup_Lobby) String() string { return proto.CompactTextString(m) }
func (*STSup_Lobby) ProtoMessage()    {}

func (m *STSup_Lobby) GetReadyState() bool {
	if m != nil && m.ReadyState != nil {
		return *m.ReadyState
	}
	return false
}

func (m *STSup_Lobby) GetShipName() string {
	if m != nil && m.ShipName != nil {
		return *m.ShipName
	}
	return ""
}

type STSup_Subscribe struct {
	NodeName         *string            `protobuf:"bytes,1,req,name=nodeName" json:"nodeName,omitempty"`
	Children         []*STSup_Subscribe `protobuf:"bytes,2,rep,name=children" json:"children,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *STSup_Subscribe) Reset()         { *m = STSup_Subscribe{} }
func (m *STSup_Subscribe) String() string { return proto.CompactTextString(m) }
func (*STSup_Subscribe) ProtoMessage()    {}

func (m *STSup_Subscribe) GetNodeName() string {
	if m != nil && m.NodeName != nil {
		return *m.NodeName
	}
	return ""
}

func (m *STSup_Subscribe) GetChildren() []*STSup_Subscribe {
	if m != nil {
		return m.Children
	}
	return nil
}

type STSup_Reactor struct {
	ReactantIntroduction *float64 `protobuf:"fixed64,1,opt,name=reactantIntroduction" json:"reactantIntroduction,omitempty"`
	CoolantIntroduction  *float64 `protobuf:"fixed64,2,opt,name=coolantIntroduction" json:"coolantIntroduction,omitempty"`
	XXX_unrecognized     []byte   `json:"-"`
}

func (m *STSup_Reactor) Reset()         { *m = STSup_Reactor{} }
func (m *STSup_Reactor) String() string { return proto.CompactTextString(m) }
func (*STSup_Reactor) ProtoMessage()    {}

func (m *STSup_Reactor) GetReactantIntroduction() float64 {
	if m != nil && m.ReactantIntroduction != nil {
		return *m.ReactantIntroduction
	}
	return 0
}

func (m *STSup_Reactor) GetCoolantIntroduction() float64 {
	if m != nil && m.CoolantIntroduction != nil {
		return *m.CoolantIntroduction
	}
	return 0
}

type STSup_PowerDistribution struct {
	LeftEngine           *bool  `protobuf:"varint,1,opt,name=leftEngine" json:"leftEngine,omitempty"`
	RightEngine          *bool  `protobuf:"varint,2,opt,name=rightEngine" json:"rightEngine,omitempty"`
	ForwardLeftThruster  *bool  `protobuf:"varint,3,opt,name=forwardLeftThruster" json:"forwardLeftThruster,omitempty"`
	ForwardRightThruster *bool  `protobuf:"varint,4,opt,name=forwardRightThruster" json:"forwardRightThruster,omitempty"`
	RearLeftThruster     *bool  `protobuf:"varint,5,opt,name=rearLeftThruster" json:"rearLeftThruster,omitempty"`
	RearRightThruster    *bool  `protobuf:"varint,6,opt,name=rearRightThruster" json:"rearRightThruster,omitempty"`
	XXX_unrecognized     []byte `json:"-"`
}

func (m *STSup_PowerDistribution) Reset()         { *m = STSup_PowerDistribution{} }
func (m *STSup_PowerDistribution) String() string { return proto.CompactTextString(m) }
func (*STSup_PowerDistribution) ProtoMessage()    {}

func (m *STSup_PowerDistribution) GetLeftEngine() bool {
	if m != nil && m.LeftEngine != nil {
		return *m.LeftEngine
	}
	return false
}

func (m *STSup_PowerDistribution) GetRightEngine() bool {
	if m != nil && m.RightEngine != nil {
		return *m.RightEngine
	}
	return false
}

func (m *STSup_PowerDistribution) GetForwardLeftThruster() bool {
	if m != nil && m.ForwardLeftThruster != nil {
		return *m.ForwardLeftThruster
	}
	return false
}

func (m *STSup_PowerDistribution) GetForwardRightThruster() bool {
	if m != nil && m.ForwardRightThruster != nil {
		return *m.ForwardRightThruster
	}
	return false
}

func (m *STSup_PowerDistribution) GetRearLeftThruster() bool {
	if m != nil && m.RearLeftThruster != nil {
		return *m.RearLeftThruster
	}
	return false
}

func (m *STSup_PowerDistribution) GetRearRightThruster() bool {
	if m != nil && m.RearRightThruster != nil {
		return *m.RearRightThruster
	}
	return false
}

type STSup_Engines struct {
	LeftEngineThrottle  *float64 `protobuf:"fixed64,1,opt,name=leftEngineThrottle" json:"leftEngineThrottle,omitempty"`
	RightEngineThrottle *float64 `protobuf:"fixed64,2,opt,name=rightEngineThrottle" json:"rightEngineThrottle,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *STSup_Engines) Reset()         { *m = STSup_Engines{} }
func (m *STSup_Engines) String() string { return proto.CompactTextString(m) }
func (*STSup_Engines) ProtoMessage()    {}

func (m *STSup_Engines) GetLeftEngineThrottle() float64 {
	if m != nil && m.LeftEngineThrottle != nil {
		return *m.LeftEngineThrottle
	}
	return 0
}

func (m *STSup_Engines) GetRightEngineThrottle() float64 {
	if m != nil && m.RightEngineThrottle != nil {
		return *m.RightEngineThrottle
	}
	return 0
}

type STSup_Thrusters struct {
	ForwardLeft      *float64 `protobuf:"fixed64,1,opt,name=forwardLeft" json:"forwardLeft,omitempty"`
	ForwardRight     *float64 `protobuf:"fixed64,2,opt,name=forwardRight" json:"forwardRight,omitempty"`
	RearLeft         *float64 `protobuf:"fixed64,3,opt,name=rearLeft" json:"rearLeft,omitempty"`
	RearRight        *float64 `protobuf:"fixed64,4,opt,name=rearRight" json:"rearRight,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *STSup_Thrusters) Reset()         { *m = STSup_Thrusters{} }
func (m *STSup_Thrusters) String() string { return proto.CompactTextString(m) }
func (*STSup_Thrusters) ProtoMessage()    {}

func (m *STSup_Thrusters) GetForwardLeft() float64 {
	if m != nil && m.ForwardLeft != nil {
		return *m.ForwardLeft
	}
	return 0
}

func (m *STSup_Thrusters) GetForwardRight() float64 {
	if m != nil && m.ForwardRight != nil {
		return *m.ForwardRight
	}
	return 0
}

func (m *STSup_Thrusters) GetRearLeft() float64 {
	if m != nil && m.RearLeft != nil {
		return *m.RearLeft
	}
	return 0
}

func (m *STSup_Thrusters) GetRearRight() float64 {
	if m != nil && m.RearRight != nil {
		return *m.RearRight
	}
	return 0
}

type STSdown struct {
	Connection        *STSdown_Connection        `protobuf:"bytes,1,opt,name=connection" json:"connection,omitempty"`
	JoinInfo          *STSdown_JoinInfo          `protobuf:"bytes,2,opt,name=joinInfo" json:"joinInfo,omitempty"`
	JoinResponse      *STSdown_JoinResponse      `protobuf:"bytes,3,opt,name=joinResponse" json:"joinResponse,omitempty"`
	Lobby             *STSdown_Lobby             `protobuf:"bytes,4,opt,name=lobby" json:"lobby,omitempty"`
	VisualSensors     *STSdown_VisualSensors     `protobuf:"bytes,5,opt,name=visualSensors" json:"visualSensors,omitempty"`
	Reactor           *STSdown_Reactor           `protobuf:"bytes,6,opt,name=reactor" json:"reactor,omitempty"`
	PowerDistribution *STSdown_PowerDistribution `protobuf:"bytes,7,opt,name=powerDistribution" json:"powerDistribution,omitempty"`
	Engines           *STSdown_Engines           `protobuf:"bytes,8,opt,name=engines" json:"engines,omitempty"`
	Thrusters         *STSdown_Thrusters         `protobuf:"bytes,9,opt,name=thrusters" json:"thrusters,omitempty"`
	XXX_unrecognized  []byte                     `json:"-"`
}

func (m *STSdown) Reset()         { *m = STSdown{} }
func (m *STSdown) String() string { return proto.CompactTextString(m) }
func (*STSdown) ProtoMessage()    {}

func (m *STSdown) GetConnection() *STSdown_Connection {
	if m != nil {
		return m.Connection
	}
	return nil
}

func (m *STSdown) GetJoinInfo() *STSdown_JoinInfo {
	if m != nil {
		return m.JoinInfo
	}
	return nil
}

func (m *STSdown) GetJoinResponse() *STSdown_JoinResponse {
	if m != nil {
		return m.JoinResponse
	}
	return nil
}

func (m *STSdown) GetLobby() *STSdown_Lobby {
	if m != nil {
		return m.Lobby
	}
	return nil
}

func (m *STSdown) GetVisualSensors() *STSdown_VisualSensors {
	if m != nil {
		return m.VisualSensors
	}
	return nil
}

func (m *STSdown) GetReactor() *STSdown_Reactor {
	if m != nil {
		return m.Reactor
	}
	return nil
}

func (m *STSdown) GetPowerDistribution() *STSdown_PowerDistribution {
	if m != nil {
		return m.PowerDistribution
	}
	return nil
}

func (m *STSdown) GetEngines() *STSdown_Engines {
	if m != nil {
		return m.Engines
	}
	return nil
}

func (m *STSdown) GetThrusters() *STSdown_Thrusters {
	if m != nil {
		return m.Thrusters
	}
	return nil
}

type STSdown_JoinInfo struct {
	AllowJoin        *bool   `protobuf:"varint,1,req,name=allowJoin" json:"allowJoin,omitempty"`
	GameIDtoken      *string `protobuf:"bytes,2,req,name=gameIDtoken" json:"gameIDtoken,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STSdown_JoinInfo) Reset()         { *m = STSdown_JoinInfo{} }
func (m *STSdown_JoinInfo) String() string { return proto.CompactTextString(m) }
func (*STSdown_JoinInfo) ProtoMessage()    {}

func (m *STSdown_JoinInfo) GetAllowJoin() bool {
	if m != nil && m.AllowJoin != nil {
		return *m.AllowJoin
	}
	return false
}

func (m *STSdown_JoinInfo) GetGameIDtoken() string {
	if m != nil && m.GameIDtoken != nil {
		return *m.GameIDtoken
	}
	return ""
}

type STSdown_JoinResponse struct {
	Type             *STSdown_JoinResponse_Type `protobuf:"varint,1,req,name=type,enum=common.STSdown_JoinResponse_Type" json:"type,omitempty"`
	RejoinToken      *string                    `protobuf:"bytes,2,opt,name=rejoinToken" json:"rejoinToken,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *STSdown_JoinResponse) Reset()         { *m = STSdown_JoinResponse{} }
func (m *STSdown_JoinResponse) String() string { return proto.CompactTextString(m) }
func (*STSdown_JoinResponse) ProtoMessage()    {}

func (m *STSdown_JoinResponse) GetType() STSdown_JoinResponse_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return STSdown_JoinResponse_JOIN_ACCEPTED
}

func (m *STSdown_JoinResponse) GetRejoinToken() string {
	if m != nil && m.RejoinToken != nil {
		return *m.RejoinToken
	}
	return ""
}

type STSdown_Connection struct {
	Connected        *bool  `protobuf:"varint,1,opt,name=connected" json:"connected,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *STSdown_Connection) Reset()         { *m = STSdown_Connection{} }
func (m *STSdown_Connection) String() string { return proto.CompactTextString(m) }
func (*STSdown_Connection) ProtoMessage()    {}

func (m *STSdown_Connection) GetConnected() bool {
	if m != nil && m.Connected != nil {
		return *m.Connected
	}
	return false
}

type STSdown_Lobby struct {
	ReadyState       *bool    `protobuf:"varint,1,opt,name=readyState" json:"readyState,omitempty"`
	ShipName         *string  `protobuf:"bytes,2,opt,name=shipName" json:"shipName,omitempty"`
	ShipsInGame      []string `protobuf:"bytes,3,rep,name=shipsInGame" json:"shipsInGame,omitempty"`
	GameStarted      *bool    `protobuf:"varint,4,opt,name=gameStarted" json:"gameStarted,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *STSdown_Lobby) Reset()         { *m = STSdown_Lobby{} }
func (m *STSdown_Lobby) String() string { return proto.CompactTextString(m) }
func (*STSdown_Lobby) ProtoMessage()    {}

func (m *STSdown_Lobby) GetReadyState() bool {
	if m != nil && m.ReadyState != nil {
		return *m.ReadyState
	}
	return false
}

func (m *STSdown_Lobby) GetShipName() string {
	if m != nil && m.ShipName != nil {
		return *m.ShipName
	}
	return ""
}

func (m *STSdown_Lobby) GetShipsInGame() []string {
	if m != nil {
		return m.ShipsInGame
	}
	return nil
}

func (m *STSdown_Lobby) GetGameStarted() bool {
	if m != nil && m.GameStarted != nil {
		return *m.GameStarted
	}
	return false
}

type STSdown_VisualSensors struct {
	SpaceObjects     []*STSdown_VisualSensors_SpaceObject `protobuf:"bytes,1,rep,name=spaceObjects" json:"spaceObjects,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *STSdown_VisualSensors) Reset()         { *m = STSdown_VisualSensors{} }
func (m *STSdown_VisualSensors) String() string { return proto.CompactTextString(m) }
func (*STSdown_VisualSensors) ProtoMessage()    {}

func (m *STSdown_VisualSensors) GetSpaceObjects() []*STSdown_VisualSensors_SpaceObject {
	if m != nil {
		return m.SpaceObjects
	}
	return nil
}

type STSdown_VisualSensors_SpaceObject struct {
	Type     *STSdown_VisualSensors_SpaceObject_Type  `protobuf:"varint,1,opt,name=type,enum=common.STSdown_VisualSensors_SpaceObject_Type" json:"type,omitempty"`
	Position *STSdown_VisualSensors_SpaceObject_Point `protobuf:"bytes,2,opt,name=position" json:"position,omitempty"`
	// orientation is in radians
	Orientation      *float64 `protobuf:"fixed64,3,opt,name=orientation" json:"orientation,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *STSdown_VisualSensors_SpaceObject) Reset()         { *m = STSdown_VisualSensors_SpaceObject{} }
func (m *STSdown_VisualSensors_SpaceObject) String() string { return proto.CompactTextString(m) }
func (*STSdown_VisualSensors_SpaceObject) ProtoMessage()    {}

func (m *STSdown_VisualSensors_SpaceObject) GetType() STSdown_VisualSensors_SpaceObject_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return STSdown_VisualSensors_SpaceObject_SHIP
}

func (m *STSdown_VisualSensors_SpaceObject) GetPosition() *STSdown_VisualSensors_SpaceObject_Point {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *STSdown_VisualSensors_SpaceObject) GetOrientation() float64 {
	if m != nil && m.Orientation != nil {
		return *m.Orientation
	}
	return 0
}

type STSdown_VisualSensors_SpaceObject_Point struct {
	X                *float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y                *float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *STSdown_VisualSensors_SpaceObject_Point) Reset() {
	*m = STSdown_VisualSensors_SpaceObject_Point{}
}
func (m *STSdown_VisualSensors_SpaceObject_Point) String() string { return proto.CompactTextString(m) }
func (*STSdown_VisualSensors_SpaceObject_Point) ProtoMessage()    {}

func (m *STSdown_VisualSensors_SpaceObject_Point) GetX() float64 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *STSdown_VisualSensors_SpaceObject_Point) GetY() float64 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type STSdown_Reactor struct {
	ReactantIntroduction *float64 `protobuf:"fixed64,1,opt,name=reactantIntroduction" json:"reactantIntroduction,omitempty"`
	CoolantIntroduction  *float64 `protobuf:"fixed64,2,opt,name=coolantIntroduction" json:"coolantIntroduction,omitempty"`
	PowerOutput          *float64 `protobuf:"fixed64,3,opt,name=powerOutput" json:"powerOutput,omitempty"`
	HeatLevel            *float64 `protobuf:"fixed64,4,opt,name=heatLevel" json:"heatLevel,omitempty"`
	XXX_unrecognized     []byte   `json:"-"`
}

func (m *STSdown_Reactor) Reset()         { *m = STSdown_Reactor{} }
func (m *STSdown_Reactor) String() string { return proto.CompactTextString(m) }
func (*STSdown_Reactor) ProtoMessage()    {}

func (m *STSdown_Reactor) GetReactantIntroduction() float64 {
	if m != nil && m.ReactantIntroduction != nil {
		return *m.ReactantIntroduction
	}
	return 0
}

func (m *STSdown_Reactor) GetCoolantIntroduction() float64 {
	if m != nil && m.CoolantIntroduction != nil {
		return *m.CoolantIntroduction
	}
	return 0
}

func (m *STSdown_Reactor) GetPowerOutput() float64 {
	if m != nil && m.PowerOutput != nil {
		return *m.PowerOutput
	}
	return 0
}

func (m *STSdown_Reactor) GetHeatLevel() float64 {
	if m != nil && m.HeatLevel != nil {
		return *m.HeatLevel
	}
	return 0
}

type STSdown_PowerDistribution struct {
	LeftEngine           *bool  `protobuf:"varint,1,opt,name=leftEngine" json:"leftEngine,omitempty"`
	RightEngine          *bool  `protobuf:"varint,2,opt,name=rightEngine" json:"rightEngine,omitempty"`
	ForwardLeftThruster  *bool  `protobuf:"varint,3,opt,name=forwardLeftThruster" json:"forwardLeftThruster,omitempty"`
	ForwardRightThruster *bool  `protobuf:"varint,4,opt,name=forwardRightThruster" json:"forwardRightThruster,omitempty"`
	RearLeftThruster     *bool  `protobuf:"varint,5,opt,name=rearLeftThruster" json:"rearLeftThruster,omitempty"`
	RearRightThruster    *bool  `protobuf:"varint,6,opt,name=rearRightThruster" json:"rearRightThruster,omitempty"`
	XXX_unrecognized     []byte `json:"-"`
}

func (m *STSdown_PowerDistribution) Reset()         { *m = STSdown_PowerDistribution{} }
func (m *STSdown_PowerDistribution) String() string { return proto.CompactTextString(m) }
func (*STSdown_PowerDistribution) ProtoMessage()    {}

func (m *STSdown_PowerDistribution) GetLeftEngine() bool {
	if m != nil && m.LeftEngine != nil {
		return *m.LeftEngine
	}
	return false
}

func (m *STSdown_PowerDistribution) GetRightEngine() bool {
	if m != nil && m.RightEngine != nil {
		return *m.RightEngine
	}
	return false
}

func (m *STSdown_PowerDistribution) GetForwardLeftThruster() bool {
	if m != nil && m.ForwardLeftThruster != nil {
		return *m.ForwardLeftThruster
	}
	return false
}

func (m *STSdown_PowerDistribution) GetForwardRightThruster() bool {
	if m != nil && m.ForwardRightThruster != nil {
		return *m.ForwardRightThruster
	}
	return false
}

func (m *STSdown_PowerDistribution) GetRearLeftThruster() bool {
	if m != nil && m.RearLeftThruster != nil {
		return *m.RearLeftThruster
	}
	return false
}

func (m *STSdown_PowerDistribution) GetRearRightThruster() bool {
	if m != nil && m.RearRightThruster != nil {
		return *m.RearRightThruster
	}
	return false
}

type STSdown_Engines struct {
	LeftEngineThrottle  *float64 `protobuf:"fixed64,1,opt,name=leftEngineThrottle" json:"leftEngineThrottle,omitempty"`
	RightEngineThrottle *float64 `protobuf:"fixed64,2,opt,name=rightEngineThrottle" json:"rightEngineThrottle,omitempty"`
	XXX_unrecognized    []byte   `json:"-"`
}

func (m *STSdown_Engines) Reset()         { *m = STSdown_Engines{} }
func (m *STSdown_Engines) String() string { return proto.CompactTextString(m) }
func (*STSdown_Engines) ProtoMessage()    {}

func (m *STSdown_Engines) GetLeftEngineThrottle() float64 {
	if m != nil && m.LeftEngineThrottle != nil {
		return *m.LeftEngineThrottle
	}
	return 0
}

func (m *STSdown_Engines) GetRightEngineThrottle() float64 {
	if m != nil && m.RightEngineThrottle != nil {
		return *m.RightEngineThrottle
	}
	return 0
}

type STSdown_Thrusters struct {
	ForwardLeft      *float64 `protobuf:"fixed64,1,opt,name=forwardLeft" json:"forwardLeft,omitempty"`
	ForwardRight     *float64 `protobuf:"fixed64,2,opt,name=forwardRight" json:"forwardRight,omitempty"`
	RearLeft         *float64 `protobuf:"fixed64,3,opt,name=rearLeft" json:"rearLeft,omitempty"`
	RearRight        *float64 `protobuf:"fixed64,4,opt,name=rearRight" json:"rearRight,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *STSdown_Thrusters) Reset()         { *m = STSdown_Thrusters{} }
func (m *STSdown_Thrusters) String() string { return proto.CompactTextString(m) }
func (*STSdown_Thrusters) ProtoMessage()    {}

func (m *STSdown_Thrusters) GetForwardLeft() float64 {
	if m != nil && m.ForwardLeft != nil {
		return *m.ForwardLeft
	}
	return 0
}

func (m *STSdown_Thrusters) GetForwardRight() float64 {
	if m != nil && m.ForwardRight != nil {
		return *m.ForwardRight
	}
	return 0
}

func (m *STSdown_Thrusters) GetRearLeft() float64 {
	if m != nil && m.RearLeft != nil {
		return *m.RearLeft
	}
	return 0
}

func (m *STSdown_Thrusters) GetRearRight() float64 {
	if m != nil && m.RearRight != nil {
		return *m.RearRight
	}
	return 0
}

func init() {
	proto.RegisterEnum("common.STSup_JoinRequest_JoinType", STSup_JoinRequest_JoinType_name, STSup_JoinRequest_JoinType_value)
	proto.RegisterEnum("common.STSup_Connection_ConnectionCommand", STSup_Connection_ConnectionCommand_name, STSup_Connection_ConnectionCommand_value)
	proto.RegisterEnum("common.STSdown_JoinResponse_Type", STSdown_JoinResponse_Type_name, STSdown_JoinResponse_Type_value)
	proto.RegisterEnum("common.STSdown_VisualSensors_SpaceObject_Type", STSdown_VisualSensors_SpaceObject_Type_name, STSdown_VisualSensors_SpaceObject_Type_value)
}
